name: menosi_cli
description: A sample command-line application.
version: 1.1.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.4

# Add regular dependencies here.
dependencies:
  path: ^1.8.0
  args: ^2.0.0
  yaml: ^3.1.0
  http: ^1.2.2
  encrypt: ^5.0.1
  crypto: ^3.0.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0

executables:
  menosi: menosi_cli